name: rijndael
description: A pure Dart implementation of the Rijndael (AES) cipher, supporting multiple block sizes, CBC mode, and various padding schemes.
version: 1.0.0
homepage: https://github.com/iteng007/rijndael
repository: https://github.com/iteng007/rijndael
topics:
  - crypto
  - encryption
  - aes
  - security

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
